apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagios
spec:
  selector:
    matchLabels:
      run: nagios
  replicas: 1
  template:
    metadata:
      labels:
        run: nagios
    spec:
      containers:
      - name: nagios
        image: jasonrivers/nagios:4.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      restartPolicy: Always
