  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  selector:
    matchLabels:
      run: spring
  replicas: 1
  template:
    metadata:
      labels:
        run: spring
    spec:
      containers:
      - name: spring
        image: vulnerables/cve-2016-4977
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 8080
        - containerPort: 443
      restartPolicy: Always
